//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lawyer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Case
    {
        public long ID { get; set; }
        public string IDClient { get; set; }
        public long IDCase { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual Client Client { get; set; }
    }
}
