//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lawyer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilesProcuration
    {
        public long ID { get; set; }
        public byte[] Date { get; set; }
        public string Title { get; set; }
        public string Extantion { get; set; }
        public Nullable<long> IDProcuration { get; set; }
    
        public virtual Procuration Procuration { get; set; }
    }
}
