//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lawyer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lawery_Session
    {
        public long ID { get; set; }
        public long IDLawery { get; set; }
        public long IDSessios { get; set; }
    
        public virtual Lawery Lawery { get; set; }
        public virtual Session Session { get; set; }
    }
}
