//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lawyer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lawery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lawery()
        {
            this.Lawery_Session = new HashSet<Lawery_Session>();
            this.Procurations = new HashSet<Procuration>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string PersonalID { get; set; }
        public string Phone { get; set; }
        public Nullable<double> Salery { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Parthday { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lawery_Session> Lawery_Session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Procuration> Procurations { get; set; }
    }
}
