//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lawyer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testEntities : DbContext
    {
        public testEntities()
            : base("name=testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Case> Cases { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Client_Case> Client_Case { get; set; }
        public virtual DbSet<Execute> Executes { get; set; }
        public virtual DbSet<EXpert> EXperts { get; set; }
        public virtual DbSet<Fee> Fees { get; set; }
        public virtual DbSet<Files_Saved> Files_Saved { get; set; }
        public virtual DbSet<FilesCas> FilesCases { get; set; }
        public virtual DbSet<FilesProcuration> FilesProcurations { get; set; }
        public virtual DbSet<Fils_Fees> Fils_Fees { get; set; }
        public virtual DbSet<Jadge> Jadges { get; set; }
        public virtual DbSet<Lawery> Laweries { get; set; }
        public virtual DbSet<Lawery_Session> Lawery_Session { get; set; }
        public virtual DbSet<Procuration> Procurations { get; set; }
        public virtual DbSet<Register> Registers { get; set; }
        public virtual DbSet<Resumption> Resumptions { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<Stuff> Stuffs { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<veto> vetoes { get; set; }
        public virtual DbSet<View_1> View_1 { get; set; }
        public virtual DbSet<ViewClient_Pro> ViewClient_Pro { get; set; }
    }
}
