//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lawyer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resumption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resumption()
        {
            this.Sessions = new HashSet<Session>();
        }
    
        public long ID_Resumption { get; set; }
        public string Tybe { get; set; }
        public string Notes { get; set; }
        public Nullable<long> Number_Of_Session { get; set; }
        public string Circle { get; set; }
    
        public virtual Resumption Resumption1 { get; set; }
        public virtual Resumption Resumption2 { get; set; }
        public virtual Resumption Resumption11 { get; set; }
        public virtual Resumption Resumption3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
